export const CIUDADES_ESPANA = [
  'A Coruna',
  'Albacete',
  'Alcala de Henares',
  'Alcobendas',
  'Alcorcon',
  'Algeciras',
  'Alicante',
  'Almeria',
  'Arrecife',
  'Avila',
  'Badajoz',
  'Badalona',
  'Barcelona',
  'Barakaldo',
  'Burgos',
  'Caceres',
  'Cadiz',
  'Cartagena',
  'Castellon de la Plana',
  'Ceuta',
  'Ciudad Real',
  'Cordoba',
  'Cuenca',
  'Dos Hermanas',
  'El Ejido',
  'Elche',
  'Ferrol',
  'Fuenlabrada',
  'Gandia',
  'Getafe',
  'Gijon',
  'Girona',
  'Granada',
  'Guadalajara',
  'Hospitalet de Llobregat',
  'Huelva',
  'Huesca',
  'Ibiza',
  'Jaen',
  'Jerez de la Frontera',
  'La Linea de la Concepcion',
  'Las Palmas de Gran Canaria',
  'Leon',
  'Lleida',
  'Logrono',
  'Lorca',
  'Lugo',
  'Madrid',
  'Malaga',
  'Marbella',
  'Melilla',
  'Merida',
  'Mijas',
  'Mostoles',
  'Murcia',
  'Ourense',
  'Oviedo',
  'Palencia',
  'Palma',
  'Pamplona',
  'Parla',
  'Pontevedra',
  'Pozuelo de Alarcon',
  'Reus',
  'Roquetas de Mar',
  'Sabadell',
  'Salamanca',
  'San Cristobal de La Laguna',
  'San Fernando',
  'San Sebastian',
  'Sant Cugat del Valles',
  'Santander',
  'Santiago de Compostela',
  'Segovia',
  'Sevilla',
  'Soria',
  'Tarragona',
  'Terrassa',
  'Toledo',
  'Torrejon de Ardoz',
  'Torrelavega',
  'Valdemoro',
  'Valencia',
  'Valladolid',
  'Vigo',
  'Vitoria-Gasteiz',
  'Zamora',
  'Zaragoza',
] as const;
